const MAIN_TEXT_COLOR: string = "#ececec";
const MAIN_TITLE_TEXT_SIZE: number = 20;
const MAIN_BACKGROUND_COLOR: string = "#4e4e4e";
const MAIN_LINE_COLOR: string = "#73e9e9";
const MAIN_BORDER_COLOR: string = "#eeeeee";
const MAIN_TEXT_BOLD_WEIGHT: number = 600;
const MAIN_PLACEHOLDER_COLOR: string = "silver";

export const HEADER_STYLE = {
    HEIGHT_NUMBER: 60,
    BOTTOM_LINE_COLOR: MAIN_LINE_COLOR,
    BACKGROUND_COLOR: MAIN_BACKGROUND_COLOR,
    TEXT_COLOR: MAIN_TEXT_COLOR, 
    TITLE_WEIGHT: MAIN_TEXT_BOLD_WEIGHT, 
    TITLE_TEXT_SIZE: MAIN_TITLE_TEXT_SIZE,
}

export const DEFAULT_STYLE = {
    TEXT_COLOR_STRING: MAIN_TEXT_COLOR,
    TEXT: {
        DEFAULT_COLOR: MAIN_TEXT_COLOR,
        INPUT_PLACEHOLDER_COLOR: MAIN_PLACEHOLDER_COLOR,
        BOLD_WEIGHT: MAIN_TEXT_BOLD_WEIGHT,
    },
    
    HOVERED: {
        BOX_SAHDOW_COLOR: MAIN_LINE_COLOR,
        BORDER_COLOR: MAIN_LINE_COLOR,
        TEXT_COLOR: MAIN_LINE_COLOR,
    }
}

export const INPUT_STYLE = {
    ACTIVE: {
        BORDER_COLOR: MAIN_LINE_COLOR,
    },
    BORDER_COLOR: MAIN_BORDER_COLOR,
}

